set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" color scheme
Plugin 'dracula/vim'
Plugin 'morhetz/gruvbox'

" syntax highlight
Plugin 'sheerun/vim-polyglot'

" editorconfig
Plugin 'editorconfig/editorconfig-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"""
set guifont=PragmataPro\ Liga:h18

" scheme
syntax on
color gruvbox
set background=dark

" search
set incsearch
set ignorecase
set smartcase

" fish shell
set shell=/bin/bash

