
if [ -r ~/.profile ]; then . ~/.profile; fi


# Functions to help us manage paths.  Second argument is the name of the
# path variable to be modified (default: PATH)
pathremove () {
    local IFS=':'
    local NEWPATH
    local DIR
    local PATHVARIABLE=${2:-PATH}
    for DIR in ${!PATHVARIABLE} ; do
        if [ "$DIR" != "$1" ] ; then
            NEWPATH=${NEWPATH:+$NEWPATH:}$DIR
        fi
    done
    export $PATHVARIABLE="$NEWPATH"
}

pathexist () {
    local IFS=':'
    local DIR
    local PATHVARIABLE=${2:-PATH}
    for DIR in ${!PATHVARIABLE} ; do
        if [ "$DIR" = "$1" ] ; then
            echo "$DIR"
        fi
    done
}

pathprepend () {
    # if [ -n `pathexist $1` ] ; then return ; fi
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="$1${!PATHVARIABLE:+:${!PATHVARIABLE}}"
}

pathappend () {
    # if [ -n `pathexist $1` ] ; then return ; fi
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="${!PATHVARIABLE:+${!PATHVARIABLE}:}$1"
}

pathprepend "/usr/local/sbin"
pathprepend "/usr/local/bin"

# home brew
alias brew='PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin brew'
export HOMEBREW_NO_ANALYTICS=1


# rbenv
# export RBENV_ROOT="$HOME/.rbenv"
# pathprepend "$RBENV_ROOT/bin"
# if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# pyenv
export PYENV_ROOT="$HOME/.pyenv"
pathprepend "$PYENV_ROOT/bin"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
#export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"


# nodenv
export NODENV_ROOT="$HOME/.nodenv"
pathprepend "$NODENV_ROOT/bin"
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi


# jenv
# pathprepend "$HOME/.jenv/bin"
# if which jenv > /dev/null; then eval "$(jenv init -)"; fi


# rust
pathprepend "$HOME/.cargo/bin"

# go path
export GOPATH="$HOME/.gocode"
pathprepend "$GOPATH/bin"


# theos
# export THEOS="/opt/theos"
# pathprepend "$THEOS/bin"

# iosopendev
# export iOSOpenDevPath=/opt/iOSOpenDev
# pathprepend "$iOSOpenDevPath/bin"
# export iOSOpenDevDevice=127.0.0.1
# export iOSOpenDevPort=2022

# ~/apps
# export ANT_HOME="$HOME/apps/apache-ant"
# pathprepend "$ANT_HOME/bin"
#
# export M2_HOME="$HOME/apps/apache-maven"
# pathprepend "$M2_HOME/bin"
#
# export SCALA_HOME="$HOME/apps/scala"
# pathprepend "$SCALA_HOME/bin"


# ~/bin is always prepended
pathprepend "$HOME/bin"

# Now to clean up
unset pathremove pathprepend pathappend


# RC
case "$-" in *i*) if [ -r ~/.bashrc ]; then . ~/.bashrc; fi;; esac
